package com.jjx.mytools.dto;

import java.io.Serializable;

import com.jjx.mytools.entity.ImporterXmlDefgKey;

public class ImporterXmlDefgDto extends ImporterXmlDefgKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.elementname
     *
     * @mbg.generated
     */
    private String elementname;
    
    private int pid;
    private int id;

	public int getPid() {
		return pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.elementname2
     *
     * @mbg.generated
     */
    private String elementname2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.elementdesc
     *
     * @mbg.generated
     */
    private String elementdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.tables
     *
     * @mbg.generated
     */
    private String tables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.fldname
     *
     * @mbg.generated
     */
    private String fldname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.flddecimal
     *
     * @mbg.generated
     */
    private Short flddecimal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.flddefault
     *
     * @mbg.generated
     */
    private String flddefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.flags
     *
     * @mbg.generated
     */
    private Short flags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.confid
     *
     * @mbg.generated
     */
    private String confid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.mainfldname
     *
     * @mbg.generated
     */
    private String mainfldname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.sheetcode
     *
     * @mbg.generated
     */
    private String sheetcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.disflags
     *
     * @mbg.generated
     */
    private Short disflags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.elementname
     *
     * @return the value of importerxmldefg.elementname
     *
     * @mbg.generated
     */
    public String getElementname() {
        return elementname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.elementname
     *
     * @param elementname the value for importerxmldefg.elementname
     *
     * @mbg.generated
     */
    public void setElementname(String elementname) {
        this.elementname = elementname == null ? null : elementname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.elementname2
     *
     * @return the value of importerxmldefg.elementname2
     *
     * @mbg.generated
     */
    public String getElementname2() {
        return elementname2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.elementname2
     *
     * @param elementname2 the value for importerxmldefg.elementname2
     *
     * @mbg.generated
     */
    public void setElementname2(String elementname2) {
        this.elementname2 = elementname2 == null ? null : elementname2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.elementdesc
     *
     * @return the value of importerxmldefg.elementdesc
     *
     * @mbg.generated
     */
    public String getElementdesc() {
        return elementdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.elementdesc
     *
     * @param elementdesc the value for importerxmldefg.elementdesc
     *
     * @mbg.generated
     */
    public void setElementdesc(String elementdesc) {
        this.elementdesc = elementdesc == null ? null : elementdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.tables
     *
     * @return the value of importerxmldefg.tables
     *
     * @mbg.generated
     */
    public String getTables() {
        return tables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.tables
     *
     * @param tables the value for importerxmldefg.tables
     *
     * @mbg.generated
     */
    public void setTables(String tables) {
        this.tables = tables == null ? null : tables.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.fldname
     *
     * @return the value of importerxmldefg.fldname
     *
     * @mbg.generated
     */
    public String getFldname() {
        return fldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.fldname
     *
     * @param fldname the value for importerxmldefg.fldname
     *
     * @mbg.generated
     */
    public void setFldname(String fldname) {
        this.fldname = fldname == null ? null : fldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.flddecimal
     *
     * @return the value of importerxmldefg.flddecimal
     *
     * @mbg.generated
     */
    public Short getFlddecimal() {
        return flddecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.flddecimal
     *
     * @param flddecimal the value for importerxmldefg.flddecimal
     *
     * @mbg.generated
     */
    public void setFlddecimal(Short flddecimal) {
        this.flddecimal = flddecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.flddefault
     *
     * @return the value of importerxmldefg.flddefault
     *
     * @mbg.generated
     */
    public String getFlddefault() {
        return flddefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.flddefault
     *
     * @param flddefault the value for importerxmldefg.flddefault
     *
     * @mbg.generated
     */
    public void setFlddefault(String flddefault) {
        this.flddefault = flddefault == null ? null : flddefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.flags
     *
     * @return the value of importerxmldefg.flags
     *
     * @mbg.generated
     */
    public Short getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.flags
     *
     * @param flags the value for importerxmldefg.flags
     *
     * @mbg.generated
     */
    public void setFlags(Short flags) {
        this.flags = flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.confid
     *
     * @return the value of importerxmldefg.confid
     *
     * @mbg.generated
     */
    public String getConfid() {
        return confid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.confid
     *
     * @param confid the value for importerxmldefg.confid
     *
     * @mbg.generated
     */
    public void setConfid(String confid) {
        this.confid = confid == null ? null : confid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.mainfldname
     *
     * @return the value of importerxmldefg.mainfldname
     *
     * @mbg.generated
     */
    public String getMainfldname() {
        return mainfldname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.mainfldname
     *
     * @param mainfldname the value for importerxmldefg.mainfldname
     *
     * @mbg.generated
     */
    public void setMainfldname(String mainfldname) {
        this.mainfldname = mainfldname == null ? null : mainfldname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.sheetcode
     *
     * @return the value of importerxmldefg.sheetcode
     *
     * @mbg.generated
     */
    public String getSheetcode() {
        return sheetcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.sheetcode
     *
     * @param sheetcode the value for importerxmldefg.sheetcode
     *
     * @mbg.generated
     */
    public void setSheetcode(String sheetcode) {
        this.sheetcode = sheetcode == null ? null : sheetcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.disflags
     *
     * @return the value of importerxmldefg.disflags
     *
     * @mbg.generated
     */
    public Short getDisflags() {
        return disflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.disflags
     *
     * @param disflags the value for importerxmldefg.disflags
     *
     * @mbg.generated
     */
    public void setDisflags(Short disflags) {
        this.disflags = disflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.remark
     *
     * @return the value of importerxmldefg.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.remark
     *
     * @param remark the value for importerxmldefg.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}