package com.jjx.mytools.dto;

import java.io.Serializable;

public class ImporterXmlDefDto implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.xmlcode
     *
     * @mbg.generated
     */
    private String xmlcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.xmlname
     *
     * @mbg.generated
     */
    private String xmlname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.charsetname
     *
     * @mbg.generated
     */
    private String charsetname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.flags
     *
     * @mbg.generated
     */
    private Short flags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.sysid
     *
     * @mbg.generated
     */
    private Short sysid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.disposeclass
     *
     * @mbg.generated
     */
    private String disposeclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.levlstep
     *
     * @mbg.generated
     */
    private Short levlstep;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldef.tac
     *
     * @mbg.generated
     */
    private String tac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.xmlcode
     *
     * @return the value of importerxmldef.xmlcode
     *
     * @mbg.generated
     */
    public String getXmlcode() {
        return xmlcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.xmlcode
     *
     * @param xmlcode the value for importerxmldef.xmlcode
     *
     * @mbg.generated
     */
    public void setXmlcode(String xmlcode) {
        this.xmlcode = xmlcode == null ? null : xmlcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.xmlname
     *
     * @return the value of importerxmldef.xmlname
     *
     * @mbg.generated
     */
    public String getXmlname() {
        return xmlname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.xmlname
     *
     * @param xmlname the value for importerxmldef.xmlname
     *
     * @mbg.generated
     */
    public void setXmlname(String xmlname) {
        this.xmlname = xmlname == null ? null : xmlname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.charsetname
     *
     * @return the value of importerxmldef.charsetname
     *
     * @mbg.generated
     */
    public String getCharsetname() {
        return charsetname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.charsetname
     *
     * @param charsetname the value for importerxmldef.charsetname
     *
     * @mbg.generated
     */
    public void setCharsetname(String charsetname) {
        this.charsetname = charsetname == null ? null : charsetname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.flags
     *
     * @return the value of importerxmldef.flags
     *
     * @mbg.generated
     */
    public Short getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.flags
     *
     * @param flags the value for importerxmldef.flags
     *
     * @mbg.generated
     */
    public void setFlags(Short flags) {
        this.flags = flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.sysid
     *
     * @return the value of importerxmldef.sysid
     *
     * @mbg.generated
     */
    public Short getSysid() {
        return sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.sysid
     *
     * @param sysid the value for importerxmldef.sysid
     *
     * @mbg.generated
     */
    public void setSysid(Short sysid) {
        this.sysid = sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.disposeclass
     *
     * @return the value of importerxmldef.disposeclass
     *
     * @mbg.generated
     */
    public String getDisposeclass() {
        return disposeclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.disposeclass
     *
     * @param disposeclass the value for importerxmldef.disposeclass
     *
     * @mbg.generated
     */
    public void setDisposeclass(String disposeclass) {
        this.disposeclass = disposeclass == null ? null : disposeclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.remark
     *
     * @return the value of importerxmldef.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.remark
     *
     * @param remark the value for importerxmldef.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.levlstep
     *
     * @return the value of importerxmldef.levlstep
     *
     * @mbg.generated
     */
    public Short getLevlstep() {
        return levlstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.levlstep
     *
     * @param levlstep the value for importerxmldef.levlstep
     *
     * @mbg.generated
     */
    public void setLevlstep(Short levlstep) {
        this.levlstep = levlstep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldef.tac
     *
     * @return the value of importerxmldef.tac
     *
     * @mbg.generated
     */
    public String getTac() {
        return tac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldef.tac
     *
     * @param tac the value for importerxmldef.tac
     *
     * @mbg.generated
     */
    public void setTac(String tac) {
        this.tac = tac == null ? null : tac.trim();
    }
}