package com.jjx.mytools.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArticleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public ArticleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andArticleIdIsNull() {
            addCriterion("article_id is null");
            return (Criteria) this;
        }

        public Criteria andArticleIdIsNotNull() {
            addCriterion("article_id is not null");
            return (Criteria) this;
        }

        public Criteria andArticleIdEqualTo(String value) {
            addCriterion("article_id =", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotEqualTo(String value) {
            addCriterion("article_id <>", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThan(String value) {
            addCriterion("article_id >", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdGreaterThanOrEqualTo(String value) {
            addCriterion("article_id >=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThan(String value) {
            addCriterion("article_id <", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLessThanOrEqualTo(String value) {
            addCriterion("article_id <=", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdLike(String value) {
            addCriterion("article_id like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotLike(String value) {
            addCriterion("article_id not like", value, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdIn(List<String> values) {
            addCriterion("article_id in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotIn(List<String> values) {
            addCriterion("article_id not in", values, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdBetween(String value1, String value2) {
            addCriterion("article_id between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleIdNotBetween(String value1, String value2) {
            addCriterion("article_id not between", value1, value2, "articleId");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNull() {
            addCriterion("article_title is null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIsNotNull() {
            addCriterion("article_title is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTitleEqualTo(String value) {
            addCriterion("article_title =", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotEqualTo(String value) {
            addCriterion("article_title <>", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThan(String value) {
            addCriterion("article_title >", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleGreaterThanOrEqualTo(String value) {
            addCriterion("article_title >=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThan(String value) {
            addCriterion("article_title <", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLessThanOrEqualTo(String value) {
            addCriterion("article_title <=", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleLike(String value) {
            addCriterion("article_title like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotLike(String value) {
            addCriterion("article_title not like", value, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleIn(List<String> values) {
            addCriterion("article_title in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotIn(List<String> values) {
            addCriterion("article_title not in", values, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleBetween(String value1, String value2) {
            addCriterion("article_title between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleTitleNotBetween(String value1, String value2) {
            addCriterion("article_title not between", value1, value2, "articleTitle");
            return (Criteria) this;
        }

        public Criteria andArticleNameIsNull() {
            addCriterion("article_name is null");
            return (Criteria) this;
        }

        public Criteria andArticleNameIsNotNull() {
            addCriterion("article_name is not null");
            return (Criteria) this;
        }

        public Criteria andArticleNameEqualTo(String value) {
            addCriterion("article_name =", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotEqualTo(String value) {
            addCriterion("article_name <>", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameGreaterThan(String value) {
            addCriterion("article_name >", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameGreaterThanOrEqualTo(String value) {
            addCriterion("article_name >=", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameLessThan(String value) {
            addCriterion("article_name <", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameLessThanOrEqualTo(String value) {
            addCriterion("article_name <=", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameLike(String value) {
            addCriterion("article_name like", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotLike(String value) {
            addCriterion("article_name not like", value, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameIn(List<String> values) {
            addCriterion("article_name in", values, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotIn(List<String> values) {
            addCriterion("article_name not in", values, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameBetween(String value1, String value2) {
            addCriterion("article_name between", value1, value2, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleNameNotBetween(String value1, String value2) {
            addCriterion("article_name not between", value1, value2, "articleName");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsIsNull() {
            addCriterion("article_keywords is null");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsIsNotNull() {
            addCriterion("article_keywords is not null");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsEqualTo(String value) {
            addCriterion("article_keywords =", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotEqualTo(String value) {
            addCriterion("article_keywords <>", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsGreaterThan(String value) {
            addCriterion("article_keywords >", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsGreaterThanOrEqualTo(String value) {
            addCriterion("article_keywords >=", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsLessThan(String value) {
            addCriterion("article_keywords <", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsLessThanOrEqualTo(String value) {
            addCriterion("article_keywords <=", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsLike(String value) {
            addCriterion("article_keywords like", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotLike(String value) {
            addCriterion("article_keywords not like", value, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsIn(List<String> values) {
            addCriterion("article_keywords in", values, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotIn(List<String> values) {
            addCriterion("article_keywords not in", values, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsBetween(String value1, String value2) {
            addCriterion("article_keywords between", value1, value2, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleKeywordsNotBetween(String value1, String value2) {
            addCriterion("article_keywords not between", value1, value2, "articleKeywords");
            return (Criteria) this;
        }

        public Criteria andArticleUseridIsNull() {
            addCriterion("article_userid is null");
            return (Criteria) this;
        }

        public Criteria andArticleUseridIsNotNull() {
            addCriterion("article_userid is not null");
            return (Criteria) this;
        }

        public Criteria andArticleUseridEqualTo(Integer value) {
            addCriterion("article_userid =", value, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridNotEqualTo(Integer value) {
            addCriterion("article_userid <>", value, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridGreaterThan(Integer value) {
            addCriterion("article_userid >", value, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_userid >=", value, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridLessThan(Integer value) {
            addCriterion("article_userid <", value, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridLessThanOrEqualTo(Integer value) {
            addCriterion("article_userid <=", value, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridIn(List<Integer> values) {
            addCriterion("article_userid in", values, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridNotIn(List<Integer> values) {
            addCriterion("article_userid not in", values, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridBetween(Integer value1, Integer value2) {
            addCriterion("article_userid between", value1, value2, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("article_userid not between", value1, value2, "articleUserid");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateIsNull() {
            addCriterion("article_createdate is null");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateIsNotNull() {
            addCriterion("article_createdate is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateEqualTo(Date value) {
            addCriterion("article_createdate =", value, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateNotEqualTo(Date value) {
            addCriterion("article_createdate <>", value, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateGreaterThan(Date value) {
            addCriterion("article_createdate >", value, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("article_createdate >=", value, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateLessThan(Date value) {
            addCriterion("article_createdate <", value, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("article_createdate <=", value, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateIn(List<Date> values) {
            addCriterion("article_createdate in", values, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateNotIn(List<Date> values) {
            addCriterion("article_createdate not in", values, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateBetween(Date value1, Date value2) {
            addCriterion("article_createdate between", value1, value2, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("article_createdate not between", value1, value2, "articleCreatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateIsNull() {
            addCriterion("article_updatedate is null");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateIsNotNull() {
            addCriterion("article_updatedate is not null");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateEqualTo(Date value) {
            addCriterion("article_updatedate =", value, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateNotEqualTo(Date value) {
            addCriterion("article_updatedate <>", value, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateGreaterThan(Date value) {
            addCriterion("article_updatedate >", value, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("article_updatedate >=", value, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateLessThan(Date value) {
            addCriterion("article_updatedate <", value, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateLessThanOrEqualTo(Date value) {
            addCriterion("article_updatedate <=", value, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateIn(List<Date> values) {
            addCriterion("article_updatedate in", values, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateNotIn(List<Date> values) {
            addCriterion("article_updatedate not in", values, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateBetween(Date value1, Date value2) {
            addCriterion("article_updatedate between", value1, value2, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleUpdatedateNotBetween(Date value1, Date value2) {
            addCriterion("article_updatedate not between", value1, value2, "articleUpdatedate");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNull() {
            addCriterion("article_status is null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIsNotNull() {
            addCriterion("article_status is not null");
            return (Criteria) this;
        }

        public Criteria andArticleStatusEqualTo(Integer value) {
            addCriterion("article_status =", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotEqualTo(Integer value) {
            addCriterion("article_status <>", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThan(Integer value) {
            addCriterion("article_status >", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_status >=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThan(Integer value) {
            addCriterion("article_status <", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusLessThanOrEqualTo(Integer value) {
            addCriterion("article_status <=", value, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusIn(List<Integer> values) {
            addCriterion("article_status in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotIn(List<Integer> values) {
            addCriterion("article_status not in", values, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusBetween(Integer value1, Integer value2) {
            addCriterion("article_status between", value1, value2, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("article_status not between", value1, value2, "articleStatus");
            return (Criteria) this;
        }

        public Criteria andArticleFlagIsNull() {
            addCriterion("article_flag is null");
            return (Criteria) this;
        }

        public Criteria andArticleFlagIsNotNull() {
            addCriterion("article_flag is not null");
            return (Criteria) this;
        }

        public Criteria andArticleFlagEqualTo(Integer value) {
            addCriterion("article_flag =", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagNotEqualTo(Integer value) {
            addCriterion("article_flag <>", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagGreaterThan(Integer value) {
            addCriterion("article_flag >", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_flag >=", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagLessThan(Integer value) {
            addCriterion("article_flag <", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagLessThanOrEqualTo(Integer value) {
            addCriterion("article_flag <=", value, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagIn(List<Integer> values) {
            addCriterion("article_flag in", values, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagNotIn(List<Integer> values) {
            addCriterion("article_flag not in", values, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagBetween(Integer value1, Integer value2) {
            addCriterion("article_flag between", value1, value2, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("article_flag not between", value1, value2, "articleFlag");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionIsNull() {
            addCriterion("article_description is null");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionIsNotNull() {
            addCriterion("article_description is not null");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionEqualTo(String value) {
            addCriterion("article_description =", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotEqualTo(String value) {
            addCriterion("article_description <>", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionGreaterThan(String value) {
            addCriterion("article_description >", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("article_description >=", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionLessThan(String value) {
            addCriterion("article_description <", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionLessThanOrEqualTo(String value) {
            addCriterion("article_description <=", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionLike(String value) {
            addCriterion("article_description like", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotLike(String value) {
            addCriterion("article_description not like", value, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionIn(List<String> values) {
            addCriterion("article_description in", values, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotIn(List<String> values) {
            addCriterion("article_description not in", values, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionBetween(String value1, String value2) {
            addCriterion("article_description between", value1, value2, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleDescriptionNotBetween(String value1, String value2) {
            addCriterion("article_description not between", value1, value2, "articleDescription");
            return (Criteria) this;
        }

        public Criteria andArticleCountIsNull() {
            addCriterion("article_count is null");
            return (Criteria) this;
        }

        public Criteria andArticleCountIsNotNull() {
            addCriterion("article_count is not null");
            return (Criteria) this;
        }

        public Criteria andArticleCountEqualTo(Integer value) {
            addCriterion("article_count =", value, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountNotEqualTo(Integer value) {
            addCriterion("article_count <>", value, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountGreaterThan(Integer value) {
            addCriterion("article_count >", value, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_count >=", value, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountLessThan(Integer value) {
            addCriterion("article_count <", value, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountLessThanOrEqualTo(Integer value) {
            addCriterion("article_count <=", value, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountIn(List<Integer> values) {
            addCriterion("article_count in", values, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountNotIn(List<Integer> values) {
            addCriterion("article_count not in", values, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountBetween(Integer value1, Integer value2) {
            addCriterion("article_count between", value1, value2, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("article_count not between", value1, value2, "articleCount");
            return (Criteria) this;
        }

        public Criteria andArticleTagIsNull() {
            addCriterion("article_tag is null");
            return (Criteria) this;
        }

        public Criteria andArticleTagIsNotNull() {
            addCriterion("article_tag is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTagEqualTo(String value) {
            addCriterion("article_tag =", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotEqualTo(String value) {
            addCriterion("article_tag <>", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagGreaterThan(String value) {
            addCriterion("article_tag >", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagGreaterThanOrEqualTo(String value) {
            addCriterion("article_tag >=", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagLessThan(String value) {
            addCriterion("article_tag <", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagLessThanOrEqualTo(String value) {
            addCriterion("article_tag <=", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagLike(String value) {
            addCriterion("article_tag like", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotLike(String value) {
            addCriterion("article_tag not like", value, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagIn(List<String> values) {
            addCriterion("article_tag in", values, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotIn(List<String> values) {
            addCriterion("article_tag not in", values, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagBetween(String value1, String value2) {
            addCriterion("article_tag between", value1, value2, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleTagNotBetween(String value1, String value2) {
            addCriterion("article_tag not between", value1, value2, "articleTag");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidIsNull() {
            addCriterion("article_menuid is null");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidIsNotNull() {
            addCriterion("article_menuid is not null");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidEqualTo(String value) {
            addCriterion("article_menuid =", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidNotEqualTo(String value) {
            addCriterion("article_menuid <>", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidGreaterThan(String value) {
            addCriterion("article_menuid >", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidGreaterThanOrEqualTo(String value) {
            addCriterion("article_menuid >=", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidLessThan(String value) {
            addCriterion("article_menuid <", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidLessThanOrEqualTo(String value) {
            addCriterion("article_menuid <=", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidLike(String value) {
            addCriterion("article_menuid like", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidNotLike(String value) {
            addCriterion("article_menuid not like", value, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidIn(List<String> values) {
            addCriterion("article_menuid in", values, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidNotIn(List<String> values) {
            addCriterion("article_menuid not in", values, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidBetween(String value1, String value2) {
            addCriterion("article_menuid between", value1, value2, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleMenuidNotBetween(String value1, String value2) {
            addCriterion("article_menuid not between", value1, value2, "articleMenuid");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIsNull() {
            addCriterion("article_type is null");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIsNotNull() {
            addCriterion("article_type is not null");
            return (Criteria) this;
        }

        public Criteria andArticleTypeEqualTo(Integer value) {
            addCriterion("article_type =", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotEqualTo(Integer value) {
            addCriterion("article_type <>", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeGreaterThan(Integer value) {
            addCriterion("article_type >", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("article_type >=", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeLessThan(Integer value) {
            addCriterion("article_type <", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeLessThanOrEqualTo(Integer value) {
            addCriterion("article_type <=", value, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeIn(List<Integer> values) {
            addCriterion("article_type in", values, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotIn(List<Integer> values) {
            addCriterion("article_type not in", values, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeBetween(Integer value1, Integer value2) {
            addCriterion("article_type between", value1, value2, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("article_type not between", value1, value2, "articleType");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameIsNull() {
            addCriterion("article_username is null");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameIsNotNull() {
            addCriterion("article_username is not null");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameEqualTo(String value) {
            addCriterion("article_username =", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameNotEqualTo(String value) {
            addCriterion("article_username <>", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameGreaterThan(String value) {
            addCriterion("article_username >", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("article_username >=", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameLessThan(String value) {
            addCriterion("article_username <", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameLessThanOrEqualTo(String value) {
            addCriterion("article_username <=", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameLike(String value) {
            addCriterion("article_username like", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameNotLike(String value) {
            addCriterion("article_username not like", value, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameIn(List<String> values) {
            addCriterion("article_username in", values, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameNotIn(List<String> values) {
            addCriterion("article_username not in", values, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameBetween(String value1, String value2) {
            addCriterion("article_username between", value1, value2, "articleUsername");
            return (Criteria) this;
        }

        public Criteria andArticleUsernameNotBetween(String value1, String value2) {
            addCriterion("article_username not between", value1, value2, "articleUsername");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table article
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}