package com.jjx.mytools.entity;

import java.io.Serializable;

public class ArticleWithBLOBs extends Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_content
     *
     * @mbg.generated
     */
    private String articleContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article.article_img
     *
     * @mbg.generated
     */
    private byte[] articleImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table article
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_content
     *
     * @return the value of article.article_content
     *
     * @mbg.generated
     */
    public String getArticleContent() {
        return articleContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_content
     *
     * @param articleContent the value for article.article_content
     *
     * @mbg.generated
     */
    public void setArticleContent(String articleContent) {
        this.articleContent = articleContent == null ? null : articleContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article.article_img
     *
     * @return the value of article.article_img
     *
     * @mbg.generated
     */
    public byte[] getArticleImg() {
        return articleImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article.article_img
     *
     * @param articleImg the value for article.article_img
     *
     * @mbg.generated
     */
    public void setArticleImg(byte[] articleImg) {
        this.articleImg = articleImg;
    }
}