package com.jjx.mytools.entity;

import java.io.Serializable;

public class DictinfoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictinfo.dict_id
     *
     * @mbg.generated
     */
    private Integer dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictinfo.dict_code
     *
     * @mbg.generated
     */
    private String dictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.dict_id
     *
     * @return the value of dictinfo.dict_id
     *
     * @mbg.generated
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.dict_id
     *
     * @param dictId the value for dictinfo.dict_id
     *
     * @mbg.generated
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.dict_code
     *
     * @return the value of dictinfo.dict_code
     *
     * @mbg.generated
     */
    public String getDictCode() {
        return dictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.dict_code
     *
     * @param dictCode the value for dictinfo.dict_code
     *
     * @mbg.generated
     */
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode == null ? null : dictCode.trim();
    }
}