package com.jjx.mytools.entity;

import java.io.Serializable;

public class Dictinfo extends DictinfoKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictinfo.dict_name
     *
     * @mbg.generated
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictinfo.dict_remark
     *
     * @mbg.generated
     */
    private String dictRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictinfo.dict_sortidx
     *
     * @mbg.generated
     */
    private Integer dictSortidx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.dict_name
     *
     * @return the value of dictinfo.dict_name
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.dict_name
     *
     * @param dictName the value for dictinfo.dict_name
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.dict_remark
     *
     * @return the value of dictinfo.dict_remark
     *
     * @mbg.generated
     */
    public String getDictRemark() {
        return dictRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.dict_remark
     *
     * @param dictRemark the value for dictinfo.dict_remark
     *
     * @mbg.generated
     */
    public void setDictRemark(String dictRemark) {
        this.dictRemark = dictRemark == null ? null : dictRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictinfo.dict_sortidx
     *
     * @return the value of dictinfo.dict_sortidx
     *
     * @mbg.generated
     */
    public Integer getDictSortidx() {
        return dictSortidx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictinfo.dict_sortidx
     *
     * @param dictSortidx the value for dictinfo.dict_sortidx
     *
     * @mbg.generated
     */
    public void setDictSortidx(Integer dictSortidx) {
        this.dictSortidx = dictSortidx;
    }
}