package com.jjx.mytools.entity;

import java.io.Serializable;
import java.util.Date;

public class Dictdef implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictdef.dict_id
     *
     * @mbg.generated
     */
    private Integer dictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictdef.dict_name
     *
     * @mbg.generated
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictdef.dict_flag
     *
     * @mbg.generated
     */
    private Integer dictFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictdef.dict_createdate
     *
     * @mbg.generated
     */
    private Date dictCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictdef.dict_updatedate
     *
     * @mbg.generated
     */
    private Date dictUpdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictdef.dict_id
     *
     * @return the value of dictdef.dict_id
     *
     * @mbg.generated
     */
    public Integer getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictdef.dict_id
     *
     * @param dictId the value for dictdef.dict_id
     *
     * @mbg.generated
     */
    public void setDictId(Integer dictId) {
        this.dictId = dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictdef.dict_name
     *
     * @return the value of dictdef.dict_name
     *
     * @mbg.generated
     */
    public String getDictName() {
        return dictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictdef.dict_name
     *
     * @param dictName the value for dictdef.dict_name
     *
     * @mbg.generated
     */
    public void setDictName(String dictName) {
        this.dictName = dictName == null ? null : dictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictdef.dict_flag
     *
     * @return the value of dictdef.dict_flag
     *
     * @mbg.generated
     */
    public Integer getDictFlag() {
        return dictFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictdef.dict_flag
     *
     * @param dictFlag the value for dictdef.dict_flag
     *
     * @mbg.generated
     */
    public void setDictFlag(Integer dictFlag) {
        this.dictFlag = dictFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictdef.dict_createdate
     *
     * @return the value of dictdef.dict_createdate
     *
     * @mbg.generated
     */
    public Date getDictCreatedate() {
        return dictCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictdef.dict_createdate
     *
     * @param dictCreatedate the value for dictdef.dict_createdate
     *
     * @mbg.generated
     */
    public void setDictCreatedate(Date dictCreatedate) {
        this.dictCreatedate = dictCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictdef.dict_updatedate
     *
     * @return the value of dictdef.dict_updatedate
     *
     * @mbg.generated
     */
    public Date getDictUpdatedate() {
        return dictUpdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictdef.dict_updatedate
     *
     * @param dictUpdatedate the value for dictdef.dict_updatedate
     *
     * @mbg.generated
     */
    public void setDictUpdatedate(Date dictUpdatedate) {
        this.dictUpdatedate = dictUpdatedate;
    }
}