package com.jjx.mytools.entity;

import java.util.ArrayList;
import java.util.List;

public class ImporterXmlDefgAttExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public ImporterXmlDefgAttExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andElementlevlIsNull() {
            addCriterion("elementlevl is null");
            return (Criteria) this;
        }

        public Criteria andElementlevlIsNotNull() {
            addCriterion("elementlevl is not null");
            return (Criteria) this;
        }

        public Criteria andElementlevlEqualTo(String value) {
            addCriterion("elementlevl =", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotEqualTo(String value) {
            addCriterion("elementlevl <>", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlGreaterThan(String value) {
            addCriterion("elementlevl >", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlGreaterThanOrEqualTo(String value) {
            addCriterion("elementlevl >=", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlLessThan(String value) {
            addCriterion("elementlevl <", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlLessThanOrEqualTo(String value) {
            addCriterion("elementlevl <=", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlLike(String value) {
            addCriterion("elementlevl like", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotLike(String value) {
            addCriterion("elementlevl not like", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlIn(List<String> values) {
            addCriterion("elementlevl in", values, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotIn(List<String> values) {
            addCriterion("elementlevl not in", values, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlBetween(String value1, String value2) {
            addCriterion("elementlevl between", value1, value2, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotBetween(String value1, String value2) {
            addCriterion("elementlevl not between", value1, value2, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andXmlcodeIsNull() {
            addCriterion("xmlcode is null");
            return (Criteria) this;
        }

        public Criteria andXmlcodeIsNotNull() {
            addCriterion("xmlcode is not null");
            return (Criteria) this;
        }

        public Criteria andXmlcodeEqualTo(String value) {
            addCriterion("xmlcode =", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotEqualTo(String value) {
            addCriterion("xmlcode <>", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeGreaterThan(String value) {
            addCriterion("xmlcode >", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeGreaterThanOrEqualTo(String value) {
            addCriterion("xmlcode >=", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLessThan(String value) {
            addCriterion("xmlcode <", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLessThanOrEqualTo(String value) {
            addCriterion("xmlcode <=", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLike(String value) {
            addCriterion("xmlcode like", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotLike(String value) {
            addCriterion("xmlcode not like", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeIn(List<String> values) {
            addCriterion("xmlcode in", values, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotIn(List<String> values) {
            addCriterion("xmlcode not in", values, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeBetween(String value1, String value2) {
            addCriterion("xmlcode between", value1, value2, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotBetween(String value1, String value2) {
            addCriterion("xmlcode not between", value1, value2, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andElementattIsNull() {
            addCriterion("elementatt is null");
            return (Criteria) this;
        }

        public Criteria andElementattIsNotNull() {
            addCriterion("elementatt is not null");
            return (Criteria) this;
        }

        public Criteria andElementattEqualTo(Short value) {
            addCriterion("elementatt =", value, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattNotEqualTo(Short value) {
            addCriterion("elementatt <>", value, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattGreaterThan(Short value) {
            addCriterion("elementatt >", value, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattGreaterThanOrEqualTo(Short value) {
            addCriterion("elementatt >=", value, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattLessThan(Short value) {
            addCriterion("elementatt <", value, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattLessThanOrEqualTo(Short value) {
            addCriterion("elementatt <=", value, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattIn(List<Short> values) {
            addCriterion("elementatt in", values, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattNotIn(List<Short> values) {
            addCriterion("elementatt not in", values, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattBetween(Short value1, Short value2) {
            addCriterion("elementatt between", value1, value2, "elementatt");
            return (Criteria) this;
        }

        public Criteria andElementattNotBetween(Short value1, Short value2) {
            addCriterion("elementatt not between", value1, value2, "elementatt");
            return (Criteria) this;
        }

        public Criteria andAttnameIsNull() {
            addCriterion("attname is null");
            return (Criteria) this;
        }

        public Criteria andAttnameIsNotNull() {
            addCriterion("attname is not null");
            return (Criteria) this;
        }

        public Criteria andAttnameEqualTo(String value) {
            addCriterion("attname =", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameNotEqualTo(String value) {
            addCriterion("attname <>", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameGreaterThan(String value) {
            addCriterion("attname >", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameGreaterThanOrEqualTo(String value) {
            addCriterion("attname >=", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameLessThan(String value) {
            addCriterion("attname <", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameLessThanOrEqualTo(String value) {
            addCriterion("attname <=", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameLike(String value) {
            addCriterion("attname like", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameNotLike(String value) {
            addCriterion("attname not like", value, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameIn(List<String> values) {
            addCriterion("attname in", values, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameNotIn(List<String> values) {
            addCriterion("attname not in", values, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameBetween(String value1, String value2) {
            addCriterion("attname between", value1, value2, "attname");
            return (Criteria) this;
        }

        public Criteria andAttnameNotBetween(String value1, String value2) {
            addCriterion("attname not between", value1, value2, "attname");
            return (Criteria) this;
        }

        public Criteria andAttdescIsNull() {
            addCriterion("attdesc is null");
            return (Criteria) this;
        }

        public Criteria andAttdescIsNotNull() {
            addCriterion("attdesc is not null");
            return (Criteria) this;
        }

        public Criteria andAttdescEqualTo(String value) {
            addCriterion("attdesc =", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescNotEqualTo(String value) {
            addCriterion("attdesc <>", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescGreaterThan(String value) {
            addCriterion("attdesc >", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescGreaterThanOrEqualTo(String value) {
            addCriterion("attdesc >=", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescLessThan(String value) {
            addCriterion("attdesc <", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescLessThanOrEqualTo(String value) {
            addCriterion("attdesc <=", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescLike(String value) {
            addCriterion("attdesc like", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescNotLike(String value) {
            addCriterion("attdesc not like", value, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescIn(List<String> values) {
            addCriterion("attdesc in", values, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescNotIn(List<String> values) {
            addCriterion("attdesc not in", values, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescBetween(String value1, String value2) {
            addCriterion("attdesc between", value1, value2, "attdesc");
            return (Criteria) this;
        }

        public Criteria andAttdescNotBetween(String value1, String value2) {
            addCriterion("attdesc not between", value1, value2, "attdesc");
            return (Criteria) this;
        }

        public Criteria andFlddefaultIsNull() {
            addCriterion("flddefault is null");
            return (Criteria) this;
        }

        public Criteria andFlddefaultIsNotNull() {
            addCriterion("flddefault is not null");
            return (Criteria) this;
        }

        public Criteria andFlddefaultEqualTo(String value) {
            addCriterion("flddefault =", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotEqualTo(String value) {
            addCriterion("flddefault <>", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultGreaterThan(String value) {
            addCriterion("flddefault >", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultGreaterThanOrEqualTo(String value) {
            addCriterion("flddefault >=", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultLessThan(String value) {
            addCriterion("flddefault <", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultLessThanOrEqualTo(String value) {
            addCriterion("flddefault <=", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultLike(String value) {
            addCriterion("flddefault like", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotLike(String value) {
            addCriterion("flddefault not like", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultIn(List<String> values) {
            addCriterion("flddefault in", values, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotIn(List<String> values) {
            addCriterion("flddefault not in", values, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultBetween(String value1, String value2) {
            addCriterion("flddefault between", value1, value2, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotBetween(String value1, String value2) {
            addCriterion("flddefault not between", value1, value2, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNull() {
            addCriterion("flags is null");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNotNull() {
            addCriterion("flags is not null");
            return (Criteria) this;
        }

        public Criteria andFlagsEqualTo(Short value) {
            addCriterion("flags =", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotEqualTo(Short value) {
            addCriterion("flags <>", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThan(Short value) {
            addCriterion("flags >", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThanOrEqualTo(Short value) {
            addCriterion("flags >=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThan(Short value) {
            addCriterion("flags <", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThanOrEqualTo(Short value) {
            addCriterion("flags <=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsIn(List<Short> values) {
            addCriterion("flags in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotIn(List<Short> values) {
            addCriterion("flags not in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsBetween(Short value1, Short value2) {
            addCriterion("flags between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotBetween(Short value1, Short value2) {
            addCriterion("flags not between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andConfidIsNull() {
            addCriterion("confid is null");
            return (Criteria) this;
        }

        public Criteria andConfidIsNotNull() {
            addCriterion("confid is not null");
            return (Criteria) this;
        }

        public Criteria andConfidEqualTo(String value) {
            addCriterion("confid =", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotEqualTo(String value) {
            addCriterion("confid <>", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidGreaterThan(String value) {
            addCriterion("confid >", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidGreaterThanOrEqualTo(String value) {
            addCriterion("confid >=", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidLessThan(String value) {
            addCriterion("confid <", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidLessThanOrEqualTo(String value) {
            addCriterion("confid <=", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidLike(String value) {
            addCriterion("confid like", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotLike(String value) {
            addCriterion("confid not like", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidIn(List<String> values) {
            addCriterion("confid in", values, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotIn(List<String> values) {
            addCriterion("confid not in", values, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidBetween(String value1, String value2) {
            addCriterion("confid between", value1, value2, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotBetween(String value1, String value2) {
            addCriterion("confid not between", value1, value2, "confid");
            return (Criteria) this;
        }

        public Criteria andDisflagsIsNull() {
            addCriterion("disflags is null");
            return (Criteria) this;
        }

        public Criteria andDisflagsIsNotNull() {
            addCriterion("disflags is not null");
            return (Criteria) this;
        }

        public Criteria andDisflagsEqualTo(Short value) {
            addCriterion("disflags =", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsNotEqualTo(Short value) {
            addCriterion("disflags <>", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsGreaterThan(Short value) {
            addCriterion("disflags >", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsGreaterThanOrEqualTo(Short value) {
            addCriterion("disflags >=", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsLessThan(Short value) {
            addCriterion("disflags <", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsLessThanOrEqualTo(Short value) {
            addCriterion("disflags <=", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsIn(List<Short> values) {
            addCriterion("disflags in", values, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsNotIn(List<Short> values) {
            addCriterion("disflags not in", values, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsBetween(Short value1, Short value2) {
            addCriterion("disflags between", value1, value2, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsNotBetween(Short value1, Short value2) {
            addCriterion("disflags not between", value1, value2, "disflags");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}