package com.jjx.mytools.entity;

import java.util.ArrayList;
import java.util.List;

public class ImporterXmlDefgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public ImporterXmlDefgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXmlcodeIsNull() {
            addCriterion("xmlcode is null");
            return (Criteria) this;
        }

        public Criteria andXmlcodeIsNotNull() {
            addCriterion("xmlcode is not null");
            return (Criteria) this;
        }

        public Criteria andXmlcodeEqualTo(String value) {
            addCriterion("xmlcode =", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotEqualTo(String value) {
            addCriterion("xmlcode <>", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeGreaterThan(String value) {
            addCriterion("xmlcode >", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeGreaterThanOrEqualTo(String value) {
            addCriterion("xmlcode >=", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLessThan(String value) {
            addCriterion("xmlcode <", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLessThanOrEqualTo(String value) {
            addCriterion("xmlcode <=", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLike(String value) {
            addCriterion("xmlcode like", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotLike(String value) {
            addCriterion("xmlcode not like", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeIn(List<String> values) {
            addCriterion("xmlcode in", values, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotIn(List<String> values) {
            addCriterion("xmlcode not in", values, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeBetween(String value1, String value2) {
            addCriterion("xmlcode between", value1, value2, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotBetween(String value1, String value2) {
            addCriterion("xmlcode not between", value1, value2, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andElementlevlIsNull() {
            addCriterion("elementlevl is null");
            return (Criteria) this;
        }

        public Criteria andElementlevlIsNotNull() {
            addCriterion("elementlevl is not null");
            return (Criteria) this;
        }

        public Criteria andElementlevlEqualTo(String value) {
            addCriterion("elementlevl =", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotEqualTo(String value) {
            addCriterion("elementlevl <>", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlGreaterThan(String value) {
            addCriterion("elementlevl >", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlGreaterThanOrEqualTo(String value) {
            addCriterion("elementlevl >=", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlLessThan(String value) {
            addCriterion("elementlevl <", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlLessThanOrEqualTo(String value) {
            addCriterion("elementlevl <=", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlLike(String value) {
            addCriterion("elementlevl like", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotLike(String value) {
            addCriterion("elementlevl not like", value, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlIn(List<String> values) {
            addCriterion("elementlevl in", values, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotIn(List<String> values) {
            addCriterion("elementlevl not in", values, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlBetween(String value1, String value2) {
            addCriterion("elementlevl between", value1, value2, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementlevlNotBetween(String value1, String value2) {
            addCriterion("elementlevl not between", value1, value2, "elementlevl");
            return (Criteria) this;
        }

        public Criteria andElementnameIsNull() {
            addCriterion("elementname is null");
            return (Criteria) this;
        }

        public Criteria andElementnameIsNotNull() {
            addCriterion("elementname is not null");
            return (Criteria) this;
        }

        public Criteria andElementnameEqualTo(String value) {
            addCriterion("elementname =", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameNotEqualTo(String value) {
            addCriterion("elementname <>", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameGreaterThan(String value) {
            addCriterion("elementname >", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameGreaterThanOrEqualTo(String value) {
            addCriterion("elementname >=", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameLessThan(String value) {
            addCriterion("elementname <", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameLessThanOrEqualTo(String value) {
            addCriterion("elementname <=", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameLike(String value) {
            addCriterion("elementname like", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameNotLike(String value) {
            addCriterion("elementname not like", value, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameIn(List<String> values) {
            addCriterion("elementname in", values, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameNotIn(List<String> values) {
            addCriterion("elementname not in", values, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameBetween(String value1, String value2) {
            addCriterion("elementname between", value1, value2, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementnameNotBetween(String value1, String value2) {
            addCriterion("elementname not between", value1, value2, "elementname");
            return (Criteria) this;
        }

        public Criteria andElementname2IsNull() {
            addCriterion("elementname2 is null");
            return (Criteria) this;
        }

        public Criteria andElementname2IsNotNull() {
            addCriterion("elementname2 is not null");
            return (Criteria) this;
        }

        public Criteria andElementname2EqualTo(String value) {
            addCriterion("elementname2 =", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2NotEqualTo(String value) {
            addCriterion("elementname2 <>", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2GreaterThan(String value) {
            addCriterion("elementname2 >", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2GreaterThanOrEqualTo(String value) {
            addCriterion("elementname2 >=", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2LessThan(String value) {
            addCriterion("elementname2 <", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2LessThanOrEqualTo(String value) {
            addCriterion("elementname2 <=", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2Like(String value) {
            addCriterion("elementname2 like", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2NotLike(String value) {
            addCriterion("elementname2 not like", value, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2In(List<String> values) {
            addCriterion("elementname2 in", values, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2NotIn(List<String> values) {
            addCriterion("elementname2 not in", values, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2Between(String value1, String value2) {
            addCriterion("elementname2 between", value1, value2, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementname2NotBetween(String value1, String value2) {
            addCriterion("elementname2 not between", value1, value2, "elementname2");
            return (Criteria) this;
        }

        public Criteria andElementdescIsNull() {
            addCriterion("elementdesc is null");
            return (Criteria) this;
        }

        public Criteria andElementdescIsNotNull() {
            addCriterion("elementdesc is not null");
            return (Criteria) this;
        }

        public Criteria andElementdescEqualTo(String value) {
            addCriterion("elementdesc =", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescNotEqualTo(String value) {
            addCriterion("elementdesc <>", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescGreaterThan(String value) {
            addCriterion("elementdesc >", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescGreaterThanOrEqualTo(String value) {
            addCriterion("elementdesc >=", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescLessThan(String value) {
            addCriterion("elementdesc <", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescLessThanOrEqualTo(String value) {
            addCriterion("elementdesc <=", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescLike(String value) {
            addCriterion("elementdesc like", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescNotLike(String value) {
            addCriterion("elementdesc not like", value, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescIn(List<String> values) {
            addCriterion("elementdesc in", values, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescNotIn(List<String> values) {
            addCriterion("elementdesc not in", values, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescBetween(String value1, String value2) {
            addCriterion("elementdesc between", value1, value2, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andElementdescNotBetween(String value1, String value2) {
            addCriterion("elementdesc not between", value1, value2, "elementdesc");
            return (Criteria) this;
        }

        public Criteria andTablesIsNull() {
            addCriterion("tables is null");
            return (Criteria) this;
        }

        public Criteria andTablesIsNotNull() {
            addCriterion("tables is not null");
            return (Criteria) this;
        }

        public Criteria andTablesEqualTo(String value) {
            addCriterion("tables =", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesNotEqualTo(String value) {
            addCriterion("tables <>", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesGreaterThan(String value) {
            addCriterion("tables >", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesGreaterThanOrEqualTo(String value) {
            addCriterion("tables >=", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesLessThan(String value) {
            addCriterion("tables <", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesLessThanOrEqualTo(String value) {
            addCriterion("tables <=", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesLike(String value) {
            addCriterion("tables like", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesNotLike(String value) {
            addCriterion("tables not like", value, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesIn(List<String> values) {
            addCriterion("tables in", values, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesNotIn(List<String> values) {
            addCriterion("tables not in", values, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesBetween(String value1, String value2) {
            addCriterion("tables between", value1, value2, "tables");
            return (Criteria) this;
        }

        public Criteria andTablesNotBetween(String value1, String value2) {
            addCriterion("tables not between", value1, value2, "tables");
            return (Criteria) this;
        }

        public Criteria andFldnameIsNull() {
            addCriterion("fldname is null");
            return (Criteria) this;
        }

        public Criteria andFldnameIsNotNull() {
            addCriterion("fldname is not null");
            return (Criteria) this;
        }

        public Criteria andFldnameEqualTo(String value) {
            addCriterion("fldname =", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotEqualTo(String value) {
            addCriterion("fldname <>", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameGreaterThan(String value) {
            addCriterion("fldname >", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameGreaterThanOrEqualTo(String value) {
            addCriterion("fldname >=", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameLessThan(String value) {
            addCriterion("fldname <", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameLessThanOrEqualTo(String value) {
            addCriterion("fldname <=", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameLike(String value) {
            addCriterion("fldname like", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotLike(String value) {
            addCriterion("fldname not like", value, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameIn(List<String> values) {
            addCriterion("fldname in", values, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotIn(List<String> values) {
            addCriterion("fldname not in", values, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameBetween(String value1, String value2) {
            addCriterion("fldname between", value1, value2, "fldname");
            return (Criteria) this;
        }

        public Criteria andFldnameNotBetween(String value1, String value2) {
            addCriterion("fldname not between", value1, value2, "fldname");
            return (Criteria) this;
        }

        public Criteria andFlddecimalIsNull() {
            addCriterion("flddecimal is null");
            return (Criteria) this;
        }

        public Criteria andFlddecimalIsNotNull() {
            addCriterion("flddecimal is not null");
            return (Criteria) this;
        }

        public Criteria andFlddecimalEqualTo(Short value) {
            addCriterion("flddecimal =", value, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalNotEqualTo(Short value) {
            addCriterion("flddecimal <>", value, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalGreaterThan(Short value) {
            addCriterion("flddecimal >", value, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalGreaterThanOrEqualTo(Short value) {
            addCriterion("flddecimal >=", value, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalLessThan(Short value) {
            addCriterion("flddecimal <", value, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalLessThanOrEqualTo(Short value) {
            addCriterion("flddecimal <=", value, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalIn(List<Short> values) {
            addCriterion("flddecimal in", values, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalNotIn(List<Short> values) {
            addCriterion("flddecimal not in", values, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalBetween(Short value1, Short value2) {
            addCriterion("flddecimal between", value1, value2, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddecimalNotBetween(Short value1, Short value2) {
            addCriterion("flddecimal not between", value1, value2, "flddecimal");
            return (Criteria) this;
        }

        public Criteria andFlddefaultIsNull() {
            addCriterion("flddefault is null");
            return (Criteria) this;
        }

        public Criteria andFlddefaultIsNotNull() {
            addCriterion("flddefault is not null");
            return (Criteria) this;
        }

        public Criteria andFlddefaultEqualTo(String value) {
            addCriterion("flddefault =", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotEqualTo(String value) {
            addCriterion("flddefault <>", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultGreaterThan(String value) {
            addCriterion("flddefault >", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultGreaterThanOrEqualTo(String value) {
            addCriterion("flddefault >=", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultLessThan(String value) {
            addCriterion("flddefault <", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultLessThanOrEqualTo(String value) {
            addCriterion("flddefault <=", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultLike(String value) {
            addCriterion("flddefault like", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotLike(String value) {
            addCriterion("flddefault not like", value, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultIn(List<String> values) {
            addCriterion("flddefault in", values, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotIn(List<String> values) {
            addCriterion("flddefault not in", values, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultBetween(String value1, String value2) {
            addCriterion("flddefault between", value1, value2, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlddefaultNotBetween(String value1, String value2) {
            addCriterion("flddefault not between", value1, value2, "flddefault");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNull() {
            addCriterion("flags is null");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNotNull() {
            addCriterion("flags is not null");
            return (Criteria) this;
        }

        public Criteria andFlagsEqualTo(Short value) {
            addCriterion("flags =", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotEqualTo(Short value) {
            addCriterion("flags <>", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThan(Short value) {
            addCriterion("flags >", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThanOrEqualTo(Short value) {
            addCriterion("flags >=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThan(Short value) {
            addCriterion("flags <", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThanOrEqualTo(Short value) {
            addCriterion("flags <=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsIn(List<Short> values) {
            addCriterion("flags in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotIn(List<Short> values) {
            addCriterion("flags not in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsBetween(Short value1, Short value2) {
            addCriterion("flags between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotBetween(Short value1, Short value2) {
            addCriterion("flags not between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andConfidIsNull() {
            addCriterion("confid is null");
            return (Criteria) this;
        }

        public Criteria andConfidIsNotNull() {
            addCriterion("confid is not null");
            return (Criteria) this;
        }

        public Criteria andConfidEqualTo(String value) {
            addCriterion("confid =", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotEqualTo(String value) {
            addCriterion("confid <>", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidGreaterThan(String value) {
            addCriterion("confid >", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidGreaterThanOrEqualTo(String value) {
            addCriterion("confid >=", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidLessThan(String value) {
            addCriterion("confid <", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidLessThanOrEqualTo(String value) {
            addCriterion("confid <=", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidLike(String value) {
            addCriterion("confid like", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotLike(String value) {
            addCriterion("confid not like", value, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidIn(List<String> values) {
            addCriterion("confid in", values, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotIn(List<String> values) {
            addCriterion("confid not in", values, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidBetween(String value1, String value2) {
            addCriterion("confid between", value1, value2, "confid");
            return (Criteria) this;
        }

        public Criteria andConfidNotBetween(String value1, String value2) {
            addCriterion("confid not between", value1, value2, "confid");
            return (Criteria) this;
        }

        public Criteria andMainfldnameIsNull() {
            addCriterion("mainfldname is null");
            return (Criteria) this;
        }

        public Criteria andMainfldnameIsNotNull() {
            addCriterion("mainfldname is not null");
            return (Criteria) this;
        }

        public Criteria andMainfldnameEqualTo(String value) {
            addCriterion("mainfldname =", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameNotEqualTo(String value) {
            addCriterion("mainfldname <>", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameGreaterThan(String value) {
            addCriterion("mainfldname >", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameGreaterThanOrEqualTo(String value) {
            addCriterion("mainfldname >=", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameLessThan(String value) {
            addCriterion("mainfldname <", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameLessThanOrEqualTo(String value) {
            addCriterion("mainfldname <=", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameLike(String value) {
            addCriterion("mainfldname like", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameNotLike(String value) {
            addCriterion("mainfldname not like", value, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameIn(List<String> values) {
            addCriterion("mainfldname in", values, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameNotIn(List<String> values) {
            addCriterion("mainfldname not in", values, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameBetween(String value1, String value2) {
            addCriterion("mainfldname between", value1, value2, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andMainfldnameNotBetween(String value1, String value2) {
            addCriterion("mainfldname not between", value1, value2, "mainfldname");
            return (Criteria) this;
        }

        public Criteria andSheetcodeIsNull() {
            addCriterion("sheetcode is null");
            return (Criteria) this;
        }

        public Criteria andSheetcodeIsNotNull() {
            addCriterion("sheetcode is not null");
            return (Criteria) this;
        }

        public Criteria andSheetcodeEqualTo(String value) {
            addCriterion("sheetcode =", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeNotEqualTo(String value) {
            addCriterion("sheetcode <>", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeGreaterThan(String value) {
            addCriterion("sheetcode >", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeGreaterThanOrEqualTo(String value) {
            addCriterion("sheetcode >=", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeLessThan(String value) {
            addCriterion("sheetcode <", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeLessThanOrEqualTo(String value) {
            addCriterion("sheetcode <=", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeLike(String value) {
            addCriterion("sheetcode like", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeNotLike(String value) {
            addCriterion("sheetcode not like", value, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeIn(List<String> values) {
            addCriterion("sheetcode in", values, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeNotIn(List<String> values) {
            addCriterion("sheetcode not in", values, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeBetween(String value1, String value2) {
            addCriterion("sheetcode between", value1, value2, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andSheetcodeNotBetween(String value1, String value2) {
            addCriterion("sheetcode not between", value1, value2, "sheetcode");
            return (Criteria) this;
        }

        public Criteria andDisflagsIsNull() {
            addCriterion("disflags is null");
            return (Criteria) this;
        }

        public Criteria andDisflagsIsNotNull() {
            addCriterion("disflags is not null");
            return (Criteria) this;
        }

        public Criteria andDisflagsEqualTo(Short value) {
            addCriterion("disflags =", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsNotEqualTo(Short value) {
            addCriterion("disflags <>", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsGreaterThan(Short value) {
            addCriterion("disflags >", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsGreaterThanOrEqualTo(Short value) {
            addCriterion("disflags >=", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsLessThan(Short value) {
            addCriterion("disflags <", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsLessThanOrEqualTo(Short value) {
            addCriterion("disflags <=", value, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsIn(List<Short> values) {
            addCriterion("disflags in", values, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsNotIn(List<Short> values) {
            addCriterion("disflags not in", values, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsBetween(Short value1, Short value2) {
            addCriterion("disflags between", value1, value2, "disflags");
            return (Criteria) this;
        }

        public Criteria andDisflagsNotBetween(Short value1, Short value2) {
            addCriterion("disflags not between", value1, value2, "disflags");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldefg
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}