package com.jjx.mytools.entity;

import java.io.Serializable;

public class ImporterXmlDefgAtt implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.elementlevl
     *
     * @mbg.generated
     */
    private String elementlevl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.xmlcode
     *
     * @mbg.generated
     */
    private String xmlcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.elementatt
     *
     * @mbg.generated
     */
    private Short elementatt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.attname
     *
     * @mbg.generated
     */
    private String attname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.attdesc
     *
     * @mbg.generated
     */
    private String attdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.flddefault
     *
     * @mbg.generated
     */
    private String flddefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.flags
     *
     * @mbg.generated
     */
    private Short flags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.confid
     *
     * @mbg.generated
     */
    private String confid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.disflags
     *
     * @mbg.generated
     */
    private Short disflags;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefgatt.tac
     *
     * @mbg.generated
     */
    private String tac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.elementlevl
     *
     * @return the value of importerxmldefgatt.elementlevl
     *
     * @mbg.generated
     */
    public String getElementlevl() {
        return elementlevl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.elementlevl
     *
     * @param elementlevl the value for importerxmldefgatt.elementlevl
     *
     * @mbg.generated
     */
    public void setElementlevl(String elementlevl) {
        this.elementlevl = elementlevl == null ? null : elementlevl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.xmlcode
     *
     * @return the value of importerxmldefgatt.xmlcode
     *
     * @mbg.generated
     */
    public String getXmlcode() {
        return xmlcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.xmlcode
     *
     * @param xmlcode the value for importerxmldefgatt.xmlcode
     *
     * @mbg.generated
     */
    public void setXmlcode(String xmlcode) {
        this.xmlcode = xmlcode == null ? null : xmlcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.elementatt
     *
     * @return the value of importerxmldefgatt.elementatt
     *
     * @mbg.generated
     */
    public Short getElementatt() {
        return elementatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.elementatt
     *
     * @param elementatt the value for importerxmldefgatt.elementatt
     *
     * @mbg.generated
     */
    public void setElementatt(Short elementatt) {
        this.elementatt = elementatt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.attname
     *
     * @return the value of importerxmldefgatt.attname
     *
     * @mbg.generated
     */
    public String getAttname() {
        return attname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.attname
     *
     * @param attname the value for importerxmldefgatt.attname
     *
     * @mbg.generated
     */
    public void setAttname(String attname) {
        this.attname = attname == null ? null : attname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.attdesc
     *
     * @return the value of importerxmldefgatt.attdesc
     *
     * @mbg.generated
     */
    public String getAttdesc() {
        return attdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.attdesc
     *
     * @param attdesc the value for importerxmldefgatt.attdesc
     *
     * @mbg.generated
     */
    public void setAttdesc(String attdesc) {
        this.attdesc = attdesc == null ? null : attdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.flddefault
     *
     * @return the value of importerxmldefgatt.flddefault
     *
     * @mbg.generated
     */
    public String getFlddefault() {
        return flddefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.flddefault
     *
     * @param flddefault the value for importerxmldefgatt.flddefault
     *
     * @mbg.generated
     */
    public void setFlddefault(String flddefault) {
        this.flddefault = flddefault == null ? null : flddefault.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.flags
     *
     * @return the value of importerxmldefgatt.flags
     *
     * @mbg.generated
     */
    public Short getFlags() {
        return flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.flags
     *
     * @param flags the value for importerxmldefgatt.flags
     *
     * @mbg.generated
     */
    public void setFlags(Short flags) {
        this.flags = flags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.confid
     *
     * @return the value of importerxmldefgatt.confid
     *
     * @mbg.generated
     */
    public String getConfid() {
        return confid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.confid
     *
     * @param confid the value for importerxmldefgatt.confid
     *
     * @mbg.generated
     */
    public void setConfid(String confid) {
        this.confid = confid == null ? null : confid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.disflags
     *
     * @return the value of importerxmldefgatt.disflags
     *
     * @mbg.generated
     */
    public Short getDisflags() {
        return disflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.disflags
     *
     * @param disflags the value for importerxmldefgatt.disflags
     *
     * @mbg.generated
     */
    public void setDisflags(Short disflags) {
        this.disflags = disflags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefgatt.tac
     *
     * @return the value of importerxmldefgatt.tac
     *
     * @mbg.generated
     */
    public String getTac() {
        return tac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefgatt.tac
     *
     * @param tac the value for importerxmldefgatt.tac
     *
     * @mbg.generated
     */
    public void setTac(String tac) {
        this.tac = tac == null ? null : tac.trim();
    }
}