package com.jjx.mytools.entity;

import java.io.Serializable;

public class ImporterXmlDefgKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.xmlcode
     *
     * @mbg.generated
     */
    private String xmlcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.elementlevl
     *
     * @mbg.generated
     */
    private String elementlevl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.xmlcode
     *
     * @return the value of importerxmldefg.xmlcode
     *
     * @mbg.generated
     */
    public String getXmlcode() {
        return xmlcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.xmlcode
     *
     * @param xmlcode the value for importerxmldefg.xmlcode
     *
     * @mbg.generated
     */
    public void setXmlcode(String xmlcode) {
        this.xmlcode = xmlcode == null ? null : xmlcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.elementlevl
     *
     * @return the value of importerxmldefg.elementlevl
     *
     * @mbg.generated
     */
    public String getElementlevl() {
        return elementlevl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.elementlevl
     *
     * @param elementlevl the value for importerxmldefg.elementlevl
     *
     * @mbg.generated
     */
    public void setElementlevl(String elementlevl) {
        this.elementlevl = elementlevl == null ? null : elementlevl.trim();
    }
}