package com.jjx.mytools.entity;

import java.util.ArrayList;
import java.util.List;

public class ImporterXmlDefExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public ImporterXmlDefExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andXmlcodeIsNull() {
            addCriterion("xmlcode is null");
            return (Criteria) this;
        }

        public Criteria andXmlcodeIsNotNull() {
            addCriterion("xmlcode is not null");
            return (Criteria) this;
        }

        public Criteria andXmlcodeEqualTo(String value) {
            addCriterion("xmlcode =", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotEqualTo(String value) {
            addCriterion("xmlcode <>", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeGreaterThan(String value) {
            addCriterion("xmlcode >", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeGreaterThanOrEqualTo(String value) {
            addCriterion("xmlcode >=", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLessThan(String value) {
            addCriterion("xmlcode <", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLessThanOrEqualTo(String value) {
            addCriterion("xmlcode <=", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeLike(String value) {
            addCriterion("xmlcode like", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotLike(String value) {
            addCriterion("xmlcode not like", value, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeIn(List<String> values) {
            addCriterion("xmlcode in", values, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotIn(List<String> values) {
            addCriterion("xmlcode not in", values, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeBetween(String value1, String value2) {
            addCriterion("xmlcode between", value1, value2, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlcodeNotBetween(String value1, String value2) {
            addCriterion("xmlcode not between", value1, value2, "xmlcode");
            return (Criteria) this;
        }

        public Criteria andXmlnameIsNull() {
            addCriterion("xmlname is null");
            return (Criteria) this;
        }

        public Criteria andXmlnameIsNotNull() {
            addCriterion("xmlname is not null");
            return (Criteria) this;
        }

        public Criteria andXmlnameEqualTo(String value) {
            addCriterion("xmlname =", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameNotEqualTo(String value) {
            addCriterion("xmlname <>", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameGreaterThan(String value) {
            addCriterion("xmlname >", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameGreaterThanOrEqualTo(String value) {
            addCriterion("xmlname >=", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameLessThan(String value) {
            addCriterion("xmlname <", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameLessThanOrEqualTo(String value) {
            addCriterion("xmlname <=", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameLike(String value) {
            addCriterion("xmlname like", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameNotLike(String value) {
            addCriterion("xmlname not like", value, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameIn(List<String> values) {
            addCriterion("xmlname in", values, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameNotIn(List<String> values) {
            addCriterion("xmlname not in", values, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameBetween(String value1, String value2) {
            addCriterion("xmlname between", value1, value2, "xmlname");
            return (Criteria) this;
        }

        public Criteria andXmlnameNotBetween(String value1, String value2) {
            addCriterion("xmlname not between", value1, value2, "xmlname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameIsNull() {
            addCriterion("charsetname is null");
            return (Criteria) this;
        }

        public Criteria andCharsetnameIsNotNull() {
            addCriterion("charsetname is not null");
            return (Criteria) this;
        }

        public Criteria andCharsetnameEqualTo(String value) {
            addCriterion("charsetname =", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameNotEqualTo(String value) {
            addCriterion("charsetname <>", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameGreaterThan(String value) {
            addCriterion("charsetname >", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameGreaterThanOrEqualTo(String value) {
            addCriterion("charsetname >=", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameLessThan(String value) {
            addCriterion("charsetname <", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameLessThanOrEqualTo(String value) {
            addCriterion("charsetname <=", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameLike(String value) {
            addCriterion("charsetname like", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameNotLike(String value) {
            addCriterion("charsetname not like", value, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameIn(List<String> values) {
            addCriterion("charsetname in", values, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameNotIn(List<String> values) {
            addCriterion("charsetname not in", values, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameBetween(String value1, String value2) {
            addCriterion("charsetname between", value1, value2, "charsetname");
            return (Criteria) this;
        }

        public Criteria andCharsetnameNotBetween(String value1, String value2) {
            addCriterion("charsetname not between", value1, value2, "charsetname");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNull() {
            addCriterion("flags is null");
            return (Criteria) this;
        }

        public Criteria andFlagsIsNotNull() {
            addCriterion("flags is not null");
            return (Criteria) this;
        }

        public Criteria andFlagsEqualTo(Short value) {
            addCriterion("flags =", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotEqualTo(Short value) {
            addCriterion("flags <>", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThan(Short value) {
            addCriterion("flags >", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsGreaterThanOrEqualTo(Short value) {
            addCriterion("flags >=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThan(Short value) {
            addCriterion("flags <", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsLessThanOrEqualTo(Short value) {
            addCriterion("flags <=", value, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsIn(List<Short> values) {
            addCriterion("flags in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotIn(List<Short> values) {
            addCriterion("flags not in", values, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsBetween(Short value1, Short value2) {
            addCriterion("flags between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andFlagsNotBetween(Short value1, Short value2) {
            addCriterion("flags not between", value1, value2, "flags");
            return (Criteria) this;
        }

        public Criteria andSysidIsNull() {
            addCriterion("sysid is null");
            return (Criteria) this;
        }

        public Criteria andSysidIsNotNull() {
            addCriterion("sysid is not null");
            return (Criteria) this;
        }

        public Criteria andSysidEqualTo(Short value) {
            addCriterion("sysid =", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotEqualTo(Short value) {
            addCriterion("sysid <>", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidGreaterThan(Short value) {
            addCriterion("sysid >", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidGreaterThanOrEqualTo(Short value) {
            addCriterion("sysid >=", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLessThan(Short value) {
            addCriterion("sysid <", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLessThanOrEqualTo(Short value) {
            addCriterion("sysid <=", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidIn(List<Short> values) {
            addCriterion("sysid in", values, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotIn(List<Short> values) {
            addCriterion("sysid not in", values, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidBetween(Short value1, Short value2) {
            addCriterion("sysid between", value1, value2, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotBetween(Short value1, Short value2) {
            addCriterion("sysid not between", value1, value2, "sysid");
            return (Criteria) this;
        }

        public Criteria andDisposeclassIsNull() {
            addCriterion("disposeclass is null");
            return (Criteria) this;
        }

        public Criteria andDisposeclassIsNotNull() {
            addCriterion("disposeclass is not null");
            return (Criteria) this;
        }

        public Criteria andDisposeclassEqualTo(String value) {
            addCriterion("disposeclass =", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassNotEqualTo(String value) {
            addCriterion("disposeclass <>", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassGreaterThan(String value) {
            addCriterion("disposeclass >", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassGreaterThanOrEqualTo(String value) {
            addCriterion("disposeclass >=", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassLessThan(String value) {
            addCriterion("disposeclass <", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassLessThanOrEqualTo(String value) {
            addCriterion("disposeclass <=", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassLike(String value) {
            addCriterion("disposeclass like", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassNotLike(String value) {
            addCriterion("disposeclass not like", value, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassIn(List<String> values) {
            addCriterion("disposeclass in", values, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassNotIn(List<String> values) {
            addCriterion("disposeclass not in", values, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassBetween(String value1, String value2) {
            addCriterion("disposeclass between", value1, value2, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andDisposeclassNotBetween(String value1, String value2) {
            addCriterion("disposeclass not between", value1, value2, "disposeclass");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andLevlstepIsNull() {
            addCriterion("levlstep is null");
            return (Criteria) this;
        }

        public Criteria andLevlstepIsNotNull() {
            addCriterion("levlstep is not null");
            return (Criteria) this;
        }

        public Criteria andLevlstepEqualTo(Short value) {
            addCriterion("levlstep =", value, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepNotEqualTo(Short value) {
            addCriterion("levlstep <>", value, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepGreaterThan(Short value) {
            addCriterion("levlstep >", value, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepGreaterThanOrEqualTo(Short value) {
            addCriterion("levlstep >=", value, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepLessThan(Short value) {
            addCriterion("levlstep <", value, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepLessThanOrEqualTo(Short value) {
            addCriterion("levlstep <=", value, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepIn(List<Short> values) {
            addCriterion("levlstep in", values, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepNotIn(List<Short> values) {
            addCriterion("levlstep not in", values, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepBetween(Short value1, Short value2) {
            addCriterion("levlstep between", value1, value2, "levlstep");
            return (Criteria) this;
        }

        public Criteria andLevlstepNotBetween(Short value1, Short value2) {
            addCriterion("levlstep not between", value1, value2, "levlstep");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldef
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table importerxmldef
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}