package com.jjx.mytools.entity;

import java.io.Serializable;

public class ImporterXmlDefgWithBLOBs extends ImporterXmlDefg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.tac
     *
     * @mbg.generated
     */
    private String tac;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importerxmldefg.tac1
     *
     * @mbg.generated
     */
    private String tac1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.tac
     *
     * @return the value of importerxmldefg.tac
     *
     * @mbg.generated
     */
    public String getTac() {
        return tac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.tac
     *
     * @param tac the value for importerxmldefg.tac
     *
     * @mbg.generated
     */
    public void setTac(String tac) {
        this.tac = tac == null ? null : tac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importerxmldefg.tac1
     *
     * @return the value of importerxmldefg.tac1
     *
     * @mbg.generated
     */
    public String getTac1() {
        return tac1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importerxmldefg.tac1
     *
     * @param tac1 the value for importerxmldefg.tac1
     *
     * @mbg.generated
     */
    public void setTac1(String tac1) {
        this.tac1 = tac1 == null ? null : tac1.trim();
    }
}