package com.jjx.mytools.entity;

import java.io.Serializable;
import java.util.Date;

public class Menu implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_id
     *
     * @mbg.generated
     */
    private Integer menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_pid
     *
     * @mbg.generated
     */
    private Integer menuPid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_url
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_sort
     *
     * @mbg.generated
     */
    private Integer menuSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_flag
     *
     * @mbg.generated
     */
    private Integer menuFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_createdate
     *
     * @mbg.generated
     */
    private Date menuCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_icon
     *
     * @mbg.generated
     */
    private String menuIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.menu_type
     *
     * @mbg.generated
     */
    private Integer menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table menu
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_id
     *
     * @return the value of menu.menu_id
     *
     * @mbg.generated
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_id
     *
     * @param menuId the value for menu.menu_id
     *
     * @mbg.generated
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_pid
     *
     * @return the value of menu.menu_pid
     *
     * @mbg.generated
     */
    public Integer getMenuPid() {
        return menuPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_pid
     *
     * @param menuPid the value for menu.menu_pid
     *
     * @mbg.generated
     */
    public void setMenuPid(Integer menuPid) {
        this.menuPid = menuPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_name
     *
     * @return the value of menu.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_name
     *
     * @param menuName the value for menu.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_url
     *
     * @return the value of menu.menu_url
     *
     * @mbg.generated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_url
     *
     * @param menuUrl the value for menu.menu_url
     *
     * @mbg.generated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_sort
     *
     * @return the value of menu.menu_sort
     *
     * @mbg.generated
     */
    public Integer getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_sort
     *
     * @param menuSort the value for menu.menu_sort
     *
     * @mbg.generated
     */
    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_flag
     *
     * @return the value of menu.menu_flag
     *
     * @mbg.generated
     */
    public Integer getMenuFlag() {
        return menuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_flag
     *
     * @param menuFlag the value for menu.menu_flag
     *
     * @mbg.generated
     */
    public void setMenuFlag(Integer menuFlag) {
        this.menuFlag = menuFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_createdate
     *
     * @return the value of menu.menu_createdate
     *
     * @mbg.generated
     */
    public Date getMenuCreatedate() {
        return menuCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_createdate
     *
     * @param menuCreatedate the value for menu.menu_createdate
     *
     * @mbg.generated
     */
    public void setMenuCreatedate(Date menuCreatedate) {
        this.menuCreatedate = menuCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_icon
     *
     * @return the value of menu.menu_icon
     *
     * @mbg.generated
     */
    public String getMenuIcon() {
        return menuIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_icon
     *
     * @param menuIcon the value for menu.menu_icon
     *
     * @mbg.generated
     */
    public void setMenuIcon(String menuIcon) {
        this.menuIcon = menuIcon == null ? null : menuIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.menu_type
     *
     * @return the value of menu.menu_type
     *
     * @mbg.generated
     */
    public Integer getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.menu_type
     *
     * @param menuType the value for menu.menu_type
     *
     * @mbg.generated
     */
    public void setMenuType(Integer menuType) {
        this.menuType = menuType;
    }
}