package com.jjx.mytools.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_password
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_createdate
     *
     * @mbg.generated
     */
    private Date userCreatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_updatedate
     *
     * @mbg.generated
     */
    private Date userUpdatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_mobil
     *
     * @mbg.generated
     */
    private String userMobil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_addr
     *
     * @mbg.generated
     */
    private String userAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_sex
     *
     * @mbg.generated
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_idcode
     *
     * @mbg.generated
     */
    private String userIdcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_flag
     *
     * @mbg.generated
     */
    private String userFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_type
     *
     * @return the value of user.user_type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_type
     *
     * @param userType the value for user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_createdate
     *
     * @return the value of user.user_createdate
     *
     * @mbg.generated
     */
    public Date getUserCreatedate() {
        return userCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_createdate
     *
     * @param userCreatedate the value for user.user_createdate
     *
     * @mbg.generated
     */
    public void setUserCreatedate(Date userCreatedate) {
        this.userCreatedate = userCreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_updatedate
     *
     * @return the value of user.user_updatedate
     *
     * @mbg.generated
     */
    public Date getUserUpdatedate() {
        return userUpdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_updatedate
     *
     * @param userUpdatedate the value for user.user_updatedate
     *
     * @mbg.generated
     */
    public void setUserUpdatedate(Date userUpdatedate) {
        this.userUpdatedate = userUpdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_mobil
     *
     * @return the value of user.user_mobil
     *
     * @mbg.generated
     */
    public String getUserMobil() {
        return userMobil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_mobil
     *
     * @param userMobil the value for user.user_mobil
     *
     * @mbg.generated
     */
    public void setUserMobil(String userMobil) {
        this.userMobil = userMobil == null ? null : userMobil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_addr
     *
     * @return the value of user.user_addr
     *
     * @mbg.generated
     */
    public String getUserAddr() {
        return userAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_addr
     *
     * @param userAddr the value for user.user_addr
     *
     * @mbg.generated
     */
    public void setUserAddr(String userAddr) {
        this.userAddr = userAddr == null ? null : userAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_sex
     *
     * @return the value of user.user_sex
     *
     * @mbg.generated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_sex
     *
     * @param userSex the value for user.user_sex
     *
     * @mbg.generated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_idcode
     *
     * @return the value of user.user_idcode
     *
     * @mbg.generated
     */
    public String getUserIdcode() {
        return userIdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_idcode
     *
     * @param userIdcode the value for user.user_idcode
     *
     * @mbg.generated
     */
    public void setUserIdcode(String userIdcode) {
        this.userIdcode = userIdcode == null ? null : userIdcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_flag
     *
     * @return the value of user.user_flag
     *
     * @mbg.generated
     */
    public String getUserFlag() {
        return userFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_flag
     *
     * @param userFlag the value for user.user_flag
     *
     * @mbg.generated
     */
    public void setUserFlag(String userFlag) {
        this.userFlag = userFlag == null ? null : userFlag.trim();
    }
}