package com.jjx.mytools.dao;

import com.jjx.mytools.entity.Dictinfo;
import com.jjx.mytools.entity.DictinfoExample;
import com.jjx.mytools.entity.DictinfoKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictinfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    long countByExample(DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int deleteByExample(DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(DictinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int insert(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int insertSelective(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    List<Dictinfo> selectByExample(DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    Dictinfo selectByPrimaryKey(DictinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dictinfo record, @Param("example") DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dictinfo record, @Param("example") DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dictinfo record);
}