package com.jjx.mytools.dao;

import com.jjx.mytools.entity.Dictdef;
import com.jjx.mytools.entity.DictdefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictdefDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    long countByExample(DictdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int deleteByExample(DictdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int insert(Dictdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int insertSelective(Dictdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    List<Dictdef> selectByExample(DictdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    Dictdef selectByPrimaryKey(Integer dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Dictdef record, @Param("example") DictdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Dictdef record, @Param("example") DictdefExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Dictdef record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dictdef
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dictdef record);
}