package com.jjx.mytools.dao;

import com.jjx.mytools.entity.ImporterXmlDefg;
import com.jjx.mytools.entity.ImporterXmlDefgExample;
import com.jjx.mytools.entity.ImporterXmlDefgKey;
import com.jjx.mytools.entity.ImporterXmlDefgWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImporterXmlDefgDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    long countByExample(ImporterXmlDefgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int deleteByExample(ImporterXmlDefgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(ImporterXmlDefgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int insert(ImporterXmlDefgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int insertSelective(ImporterXmlDefgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    List<ImporterXmlDefgWithBLOBs> selectByExampleWithBLOBs(ImporterXmlDefgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    List<ImporterXmlDefg> selectByExample(ImporterXmlDefgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    ImporterXmlDefgWithBLOBs selectByPrimaryKey(ImporterXmlDefgKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ImporterXmlDefgWithBLOBs record, @Param("example") ImporterXmlDefgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ImporterXmlDefgWithBLOBs record, @Param("example") ImporterXmlDefgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ImporterXmlDefg record, @Param("example") ImporterXmlDefgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ImporterXmlDefgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ImporterXmlDefgWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ImporterXmlDefg record);
}