package com.jjx.mytools.dao;

import com.jjx.mytools.entity.ImporterXmlDefgAtt;
import com.jjx.mytools.entity.ImporterXmlDefgAttExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImporterXmlDefgAttDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    long countByExample(ImporterXmlDefgAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int deleteByExample(ImporterXmlDefgAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String elementlevl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int insert(ImporterXmlDefgAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int insertSelective(ImporterXmlDefgAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    List<ImporterXmlDefgAtt> selectByExampleWithBLOBs(ImporterXmlDefgAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    List<ImporterXmlDefgAtt> selectByExample(ImporterXmlDefgAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    ImporterXmlDefgAtt selectByPrimaryKey(String elementlevl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ImporterXmlDefgAtt record, @Param("example") ImporterXmlDefgAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ImporterXmlDefgAtt record, @Param("example") ImporterXmlDefgAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ImporterXmlDefgAtt record, @Param("example") ImporterXmlDefgAttExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ImporterXmlDefgAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ImporterXmlDefgAtt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importerxmldefgatt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ImporterXmlDefgAtt record);
}